services:
  audio-bot:
    image: kdidtech/discord-audio-bot:latest
    environment:
      - DISCORD_BOT_TOKEN=your-discord-bot-token-here
    volumes:
      - ./data/audio/sounds:/app/data/audio/sounds
    restart: always
